import { ActorOptions } from "../Actor";

export const squimpyChampion: Partial<ActorOptions> = {
  glyph: "ChampionSquimpy",
  name: "boulder squimp",
  colour: "cyan",
  ai: "wander",
  maxHp: 28,
  maxHpRange: 33,
  sp: 15,
  spRange: 17,
  dp: 9,
  dpRange: 12,
  attackRange: 2,
  experience: 45,
  lore: 'Grey, thick skinned cousins of the usual Squimpy often referred to as the Boulder Squimp. Oddly popular among teenage culture for their grim expression and jagged hide, the appearance of a Boulder Squimp is often used when promoting the fuzzy guitar-laden music genre known as "Gray-Blast". ',
};

export const busterChampion: Partial<ActorOptions> = {
  glyph: "ChampionBuster",
  name: "horned buster",
  colour: "yellow",
  ai: "wander",
  maxHp: 25,
  maxHpRange: 29,
  sp: 20,
  spRange: 23,
  dp: 10,
  dpRange: 13,
  experience: 55,
  lore: "Feral evolutionary relatives of the more common domesticated Buster, a Horned Buster is often seen as an omen of bad spirits or demons. Shamans of ancient tribes would hollow out their horns, blowing into them like an instrument to call to the other side for assistance with deeds both fair and foul.",
};

export const canandraChampion: Partial<ActorOptions> = {
  glyph: "ChampionCanandra",
  name: "abyssal canandra",
  colour: "purple",
  ai: "wander",
  canClimb: true,
  maxHp: 105,
  maxHpRange: 115,
  sp: 39,
  spRange: 42,
  dp: 26,
  dpRange: 32,
  experience: 1500,
  lore: "Sporting two heads and countless rigid spines, an Abyssal Canandra is a rare phenomena. Often, a conjoined Canandra will die not long after it emerges from it's mother's egg, yet a small handful survive and grow to become vicious and skilled hunters. There are no known survivors of a physical encounter with an Abyssal Canandra.",
};

export const crimChampion: Partial<ActorOptions> = {
  glyph: "ChampionCrim",
  name: "widow crim",
  colour: "blue",
  ai: "wander",
  maxHp: 66,
  maxHpRange: 72,
  sp: 25,
  spRange: 28,
  dp: 23,
  dpRange: 26,
  experience: 650,
  lore: "A portion of female Crims choose to not find shells, flaunting their barbed tail and spotted skin to attract mates. Once a Widow Crim attracts one and finishes their mating ritual, they kill and feast on them before beginning the process of laying their clutch and burying it in deep sands. Widow Crims then become aggressively territorial, attacking anything that comes near their children.",
};

export const flazzaChampion: Partial<ActorOptions> = {
  glyph: "ChampionFlazza",
  name: "stinging flazza",
  colour: "pink",
  ai: "fly",
  obeysGravity: false,
  maxHp: 43,
  maxHpRange: 48,
  sp: 24,
  spRange: 29,
  dp: 22,
  dpRange: 25,
  experience: 500,
  lore: "When a Flazza becomes old enough, it will cocoon within it's tentacles for a few weeks before emerging as the Stinging Flazza. Unlike their counterparts, Stinging Flazzas are a menace to anything around them, and are capable of living in both light and dark environments and have rapidly been spreading to regions well beyond their native environments. Rarely, allergic reactions to their stings can cause substantial harm.",
};

export const glovaChampion: Partial<ActorOptions> = {
  glyph: "ChampionGlova",
  name: "carrion glova",
  colour: "red",
  ai: "wander",
  maxHp: 25,
  maxHpRange: 29,
  sp: 23,
  spRange: 27,
  dp: 20,
  dpRange: 23,
  experience: 150,
  lore: "Under unique circumstances, a Glova that eats more meat than plant life can begin developing flesh like characteristics and become known as a Carrion Glova. They most often resemble faces, developing mouths to feed with when they become too dense with viscera. Carrion Glovas move in an unsettling fashion resembling congealed blood given sentience.",
};

export const mulnChampion: Partial<ActorOptions> = {
  glyph: "ChampionMuln",
  name: "crested muln",
  colour: "brown",
  ai: "wander",
  maxHp: 53,
  maxHpRange: 60,
  sp: 25,
  spRange: 29,
  dp: 24,
  dpRange: 28,
  experience: 850,
  lore: "Distinguishable from a regular Muln by the pattern on their chest and distinct color, Crested Muln are even more of a menace than a regular one. They are known for their high level of intelligence, often creating fake burrows to lure farmers and predators away from their actual tunnels. Rumours have it a pack of Crested Muln once sank the lost kingdom of Malteen into the depths of the earth, never to be seen again.",
};

export const slobberfinChampion: Partial<ActorOptions> = {
  glyph: "ChampionSlobberfin",
  name: "razorback slobberfin",
  colour: "blue",
  ai: "wander",
  maxHp: 95,
  maxHpRange: 105,
  sp: 38,
  spRange: 42,
  dp: 28,
  dpRange: 33,
  experience: 1100,
  lore: "Razorback Slobberfins are born without sight, relying on a keen sense of hearing and jaws that can shatter bones and rend metals to eviscerate prey and survive. A hungry Razorback is a deadly Razorback, and while significantly less active than their counterparts they are unstoppable once they leave their den to feast.",
};

export const splinterChampion: Partial<ActorOptions> = {
  glyph: "ChampionSplinter",
  name: "splinter mystic",
  colour: "yellow",
  ai: "wander",
  canClimb: true,
  maxHp: 52,
  maxHpRange: 55,
  sp: 29,
  spRange: 33,
  dp: 24,
  dpRange: 30,
  attackRange: 3,
  experience: 800,
  lore: "Further Dwelvarkian religious texts describe larger Splinters that would slowly manifest humanistic traits. They believed these Splinter Mystics would eventually grow and infiltrate human towns, passing off as travellers before invading and taking revenge for their fallen ancestor. Many believe that we are all actually Splinters ourselves and that we are all a small piece of the fallen tree, carved out in the image of the divine creator that once planted it.",
};

export const teldenChampion: Partial<ActorOptions> = {
  glyph: "ChampionTelden",
  name: "exo telden",
  colour: "cyan",
  ai: "fly",
  obeysGravity: false,
  maxHp: 40,
  maxHpRange: 43,
  sp: 23,
  spRange: 26,
  dp: 15,
  dpRange: 19,
  attackRange: 2,
  experience: 500,
  lore: "Furthering the annelid or mammal debate, Exo Teldens are a rare species that have an exposed skeletal structure. A tell-tale sign when one approaches is an extremely loud clattering and low guttural growl reminiscent of the sound a large hollow pipe struggling to drain it's contents would make. They are every bit as dangerous and noxious as their flesh and blood relatives. ",
};

export const puffusChampion: Partial<ActorOptions> = {
  glyph: "ChampionPuffus",
  name: "poison puffus",
  colour: "blue",
  ai: "wander",
  needsWater: true,
  maxHp: 44,
  maxHpRange: 52,
  sp: 25,
  spRange: 29,
  dp: 15,
  dpRange: 23,
  experience: 200,
  lore: "Exotic stripes and beautiful patterns betray the Poison Puffus of it's actual danger. Coated in a light poison that causes a burning sensation, a threatened Poison Puffus will also inflate to almost double it's size, baring sharp fangs capable of causing severe lacerations. Poison Puffus are considered a delicacy in many dishes, and if prepared wrong they can cause a complete body shutdown when ingested.",
};

export const shockwormChampion: Partial<ActorOptions> = {
  glyph: "ChampionShockworm",
  name: "deep shockworm",
  colour: "turquoise",
  ai: "fly",
  needsWater: true,
  maxHp: 61,
  maxHpRange: 68,
  sp: 35,
  spRange: 38,
  dp: 22,
  dpRange: 26,
  attackRange: 3,
  experience: 1000,
  lore: "Found at deeper depths than even the Shockworm, the Deep Shockworm is also deadlier. The amplitude of their voltage is far higher, and their presence is immediately known if a tingling sensation is felt when entering any body of water. Deep Shockworms are further proof for theorists towards the existence of Breshava Trenchworms, bearing a similar eye like mouth described in the legends as that of the trenchworms.",
};

export const kreebusChampion: Partial<ActorOptions> = {
  glyph: "ChampionKreebus",
  name: "kreebus prime",
  colour: "yellow",
  ai: "fly",
  obeysGravity: false,
  maxHp: 76,
  maxHpRange: 82,
  sp: 36,
  spRange: 39,
  dp: 26,
  dpRange: 29,
  attackRange: 2,
  experience: 1200,
  lore: "An elongated snout and ability to produce searing heat reaching temperatures reminiscent to that of volcanic magma distinguishes the Kreebus Prime from the regular Kreebus. Generally, the Kreebus Prime is observed to be non-aggressive, and yet close contact is impossible due to their extreme body heat. Perhaps their very existence is punishment for the crimes dragon-kind once committed upon the world, doomed to a life of lonely drifting.",
};

export const grundillaChampion: Partial<ActorOptions> = {
  glyph: "ChampionGrundilla",
  name: "alpha grundilla",
  colour: "blue",
  ai: "wander",
  canClimb: true,
  maxHp: 130,
  maxHpRange: 150,
  sp: 50,
  spRange: 53,
  dp: 33,
  dpRange: 38,
  experience: 1600,
  lore: "Alpha Grundillas are pack leaders by nature, taking control of small throngs of Grundillas and keeping their pack together and safe from other territorial predators and hunters alike. When faced with any sort of threat, Alpha Grundillas fly into an uncontrollable rage unlike anything imaginable, savagely brutalizing their target until there's nothing left.",
};

export const poregonChampion: Partial<ActorOptions> = {
  glyph: "ChampionPoregon",
  name: "poregon shaman",
  colour: "yellow",
  ai: "wander",
  canClimb: true,
  maxHp: 36,
  maxHpRange: 40,
  sp: 21,
  spRange: 24,
  dp: 20,
  dpRange: 24,
  attackRange: 2,
  experience: 600,
  lore: 'More sinister than their mischievous peers, Poregon Shamans preach omens of a world coated in dripping black clouds. Translated texts from their ancient language tell of the mountain Isole, far across the charted reaches of the Aelonic Ocean and beyond the arid deserts of Ziyadima, where the everyone\'s deepest wishes and nightmares play out endlessly within "The Great Orobourus" born of dishonest desires and sprouted from the ancient "Neverseed."',
};
