import { ActorOptions } from "./Actor";

export const player: Partial<ActorOptions> = {
  glyph: "@",
  name: "you",
  article: "",
  canClimb: true,
  maxHp: 80,
  maxAp: 150,
  sp: 8,
  dp: 8,
  inventorySize: 20,
};

export const squimpy: Partial<ActorOptions> = {
  glyph: "Squimpy",
  name: "squimpy",
  colour: "yellow",
  ai: "wander",
  maxHp: 24,
  maxHpRange: 28,
  sp: 13,
  spRange: 16,
  dp: 4,
  dpRange: 7,
  experience: 25,
  lore: "Born with only a single eye to see and a mouth to eat, the Squimpy is not to be confused with its eldest evolutionary relative, the Fachan. While generally harmless, if agitated or provoked the Squimpy is known for its surprisingly potent and harmful saliva that, when left untreated, is capable of leaving severe scarring akin to that of a burn.",
};
export const buster: Partial<ActorOptions> = {
  glyph: "Buster",
  name: "buster",
  colour: "pink",
  ai: "wander",
  maxHp: 20,
  maxHpRange: 25,
  sp: 18,
  spRange: 20,
  dp: 6,
  dpRange: 9,
  experience: 20,
  lore: "These odd, toad-like creatures can be found at every corner of Gantella, but none is quite as strange as those found around Lessonus. A popular domesticated pet, the strange swirl adorning their head is not hair, but a small tail like appendage that wags when stimulated. Don't be fooled, however, in the wild a Buster earns its name by growing to the size of a large dog and throwing its own weight relentlessly at anything it sees as a threat.",
};
export const canandra: Partial<ActorOptions> = {
  glyph: "Canandra",
  name: "canandra",
  colour: "orange",
  ai: "wander",
  canClimb: true,
  maxHp: 90,
  maxHpRange: 100,
  sp: 35,
  spRange: 38,
  dp: 22,
  dpRange: 26,
  experience: 800,
  lore: "Canandras should be avoided at all costs in the wild, sporting the fifth deadliest venom in the world and a constricting grip that few escape from and fewer live to tell tales about. It's advised if you're voyaging into hot, dry areas to be always aware of your surroundings and to listen for the distinctive clacking of their quills and the sound of their territorial hiss. If bitten, seek medical attention immediately.",
};
export const crim: Partial<ActorOptions> = {
  glyph: "Crim",
  name: "crim",
  colour: "red",
  ai: "wander",
  maxHp: 85,
  maxHpRange: 95,
  sp: 17,
  spRange: 21,
  dp: 28,
  dpRange: 30,
  experience: 450,
  lore: 'Also known as the "Screaming Shells" due to their rather odd facial structure, Crims are very self oriented creatures. They come out rarely to eat and then spend weeks hibernating within their shell while their food slowly digests. Crims are best left alone when encountered and tend to only become hostile when threatened or provoked.',
};
export const flazza: Partial<ActorOptions> = {
  glyph: "Flazza",
  name: "flazza",
  colour: "cyan",
  ai: "fly",
  obeysGravity: false,
  maxHp: 35,
  maxHpRange: 40,
  sp: 22,
  spRange: 26,
  dp: 18,
  dpRange: 21,
  experience: 300,
  lore: 'Tentacled flying menaces that love the dark, Flazzas are known as the "Terror Flies of the Deep". They capture any prey smaller than them by dive bombing from above attempting to break bones or outright kill their prey on the spot, should that fail they have a nasty tendency to envelop their victim within their carnivorous tentacles. They have an aversion to bright lights and thankfully keep their homes far below anywhere they\'d become a real problem.',
};
export const glova: Partial<ActorOptions> = {
  glyph: "Glova",
  name: "glova",
  colour: "white",
  ai: "wander",
  canClimb: true,
  maxHp: 18,
  maxHpRange: 23,
  sp: 20,
  spRange: 22,
  dp: 15,
  dpRange: 19,
  experience: 80,
  lore: "Comprised of bubbly acidic slime-like globules, Glovas are only ever seen below ground. Their translucent bodies often envelop and break down material slowly, allowing them to feed on moss and other natural growths, due to the potency of their slime, however, they have a tendency to eat through many other things and are best left to themselves whenever possible.",
};
export const muln: Partial<ActorOptions> = {
  glyph: "Muln",
  name: "muln",
  colour: "blue",
  ai: "wander",
  maxHp: 48,
  maxHpRange: 55,
  sp: 22,
  spRange: 26,
  dp: 20,
  dpRange: 24,
  experience: 650,
  lore: "Burrowing menaces responsible for missing crops, livestock and occasionally children, Muln cause extreme agricultural grief and property damage in many areas surrounded by mountains or cave systems. When faced with a Muln problem, it's often recommended to call in professionals to trap and relocate them to more natural habitats, and it's strongly advised to avoid Muln habitats and evacuate immediately in case of infestation.", // TODO: 'habitat' repetition
};
export const slobberfin: Partial<ActorOptions> = {
  glyph: "Slobberfin",
  name: "slobberfin",
  colour: "turquoise",
  ai: "wander",
  maxHp: 70,
  maxHpRange: 80,
  sp: 38,
  spRange: 42,
  dp: 24,
  dpRange: 28,
  experience: 700,
  lore: "Deadly both in the water and on land, Slobberfins are the number one cause of animal related deaths across Gantella. Slobberfins are highly territorial and highly adaptable creatures, and the only thing standing between them and becoming apex predators is their extreme near sightedness and pension for living in cool and dark locales.",
};
export const splinter: Partial<ActorOptions> = {
  glyph: "Splinter",
  name: "splinter",
  colour: "brown",
  ai: "wander",
  canClimb: true,
  maxHp: 45,
  maxHpRange: 50,
  sp: 26,
  spRange: 29,
  dp: 22,
  dpRange: 26,
  experience: 500,
  lore: "According to religious texts recovered from Dwelvarkian ruins, Splinters are the remains of the largest tree to have ever existed, and a source from which the Dwelvarkians themselves spurned. During a war that lasted through the birth and death of the first sun to hang in the sky, a greedy and selfish race since scrubbed from history cut the tree down, taking it's limbs for themselves and fashioning their own creatures. The Splinters came not long after, seeking revenge and entangling those unfortunate enough to cross them within their roots.",
};
export const telden: Partial<ActorOptions> = {
  glyph: "Telden",
  name: "telden",
  colour: "red",
  ai: "fly",
  obeysGravity: false,
  maxHp: 40,
  maxHpRange: 43,
  sp: 23,
  spRange: 26,
  dp: 15,
  dpRange: 19,
  experience: 500,
  lore: "Heated debates about whether Teldens originated from mammals or annelids still permeate many historical and evolutionary discussions around this bizarre creature. Regardless of which side you take, the Telden certainly won't take yours; its deadly tongue and hideous breath leave behind an odour noxious enough that it's widely considered as deadly as the thickest gasses. They are rarely seen outside of their natural dark underground habitats and should be avoided whenever possible.",
};
export const floater: Partial<ActorOptions> = {
  glyph: "InkFloater",
  name: "floater",
  colour: "darkblue",
  ai: "fly",
  obeysGravity: false,
  inky: true,
  // TODO: mimic random flying enemy
  maxHp: 75,
  maxHpRange: 85,
  sp: 32,
  spRange: 35,
  dp: 23,
  dpRange: 25,
  experience: 800,
  lore: "\"If this is not a trick or hallucination of oxygen deprived madness, this conjoined face seems to almost lament its state of being. I must stay clear of these foul things, the stench is unfathomable and I can't be sure its touch isn't fatal in some way.\"\n- Jacques Splintertooth",
};
export const drifter: Partial<ActorOptions> = {
  glyph: "InkDrifter",
  name: "drifter",
  colour: "darkblue",
  ai: "wander",
  inky: true,
  canClimb: true,
  // TODO: mimic random ground enemy
  maxHp: 80,
  maxHpRange: 90,
  sp: 32,
  spRange: 35,
  dp: 25,
  dpRange: 28,
  experience: 800,
  lore: "\"I don't understand how, but this strange abomination drifts and glides about like a feather, mimicking movements of human and beast alike. It unsettles me greatly to know things like this exist in the world, but I've come too far to give up now!\"\n- Jacques Splintertooth",
};
export const theInk: Partial<ActorOptions> = {
  glyph: "Ink1",
  name: "ink",
  article: "the",
  colour: "purple",
  inky: true,
  obeysGravity: false,
  maxHp: 200,
  maxHpRange: 220,
  sp: 45,
  spRange: 48,
  dp: 28,
  dpRange: 32,
  experience: 3000,
  teleportThreshold: 30,
  lore: "\"Whatever this hideous creature is, it's far from cognizant of what's occurring around it. Strange beasts and horrifying grotesques spurn forth endlessly from this flying yolk of terror, as if ink dripping on tarnished paper. I must report this finding, I must know why it is here, and I know I must be closer than ever to the Wisher's Fragment.\"\n- Jacques Splintertooth",
};

export const puffus: Partial<ActorOptions> = {
  glyph: "Puffus",
  name: "puffus",
  colour: "blue",
  ai: "fly", // TODO: "wanderSwim"
  obeysGravity: false,
  maxHp: 39,
  maxHpRange: 47,
  sp: 21,
  spRange: 24,
  dp: 10,
  dpRange: 13,
  experience: 45,
  lore: "Native to deep and cool waters, Puffus are largely content tend to feed off various algae and microscopic fish. When threatened or attacked they will swell to over double their initial size, exposing highly painful barbs that can leave tingling and numbness in the affected wound for weeks. Take care not to step on one when diving!",
};

export const shockworm: Partial<ActorOptions> = {
  glyph: "Shockworm",
  name: "shockworm",
  colour: "green",
  ai: "fly", // TODO: "swim"
  obeysGravity: false,
  maxHp: 56,
  maxHpRange: 62,
  sp: 32,
  spRange: 34,
  dp: 18,
  dpRange: 24,
  experience: 600,
  lore: 'Also commonly known as "Glowtubes" and "Sparknoodles", Shockworms inhabit both fresh and salt water habitats where it\'s dark. These sea predators can send massive voltage throughout their body and the surrounding body of water, making them harmful to local wildlife and most creatures of smaller stature than them. They may be related to the Breshava Megaworm, if such a thing actually exists.',
};

export const kreebus: Partial<ActorOptions> = {
  glyph: "Kreebus",
  name: "kreebus",
  colour: "pink",
  ai: "fly",
  obeysGravity: false,
  maxHp: 68,
  maxHpRange: 75,
  sp: 32,
  spRange: 35,
  dp: 23,
  dpRange: 26,
  experience: 800,
  lore: "Descended from ancient sea dragons of ages long past, the Kreebus was first sighted in the waters of the Aelonic Ocean. It is unknown how, but these vicious mini sea dragons are capable of flight through magical property alone and are relentlessly aggressive when approached. They are capable of defending themselves with short bursts of searing flame, and as such it's recommended to be wary of unusually warm waters in locales that normally wouldn't have them.",
};

export const grundilla: Partial<ActorOptions> = {
  glyph: "Grundilla",
  name: "grundilla",
  colour: "yellow",
  ai: "wander",
  canClimb: true,
  maxHp: 115,
  maxHpRange: 130,
  sp: 45,
  spRange: 50,
  dp: 30,
  dpRange: 35,
  experience: 950,
  lore: "An enraged Grundilla is said to be one of nature's most horrifying phenomena. Capable of crawling across almost any terrain and ambushing unsuspecting prey, Grundilla's evolved from a peaceful cave and forest dwelling-species into a violent powerhouse after years of over hunting. While they are still nearly extinct, their population has started to stabilize again and it's recommended to retreat as swiftly and quietly as possible should you meet one.",
};

export const poregon: Partial<ActorOptions> = {
  glyph: "Poregon",
  name: "poregon",
  colour: "cyan",
  ai: "wander",
  canClimb: true,
  maxHp: 38,
  maxHpRange: 44,
  sp: 18,
  spRange: 22,
  dp: 18,
  dpRange: 22,
  experience: 350,
  lore: "A strange race of creatures that are said to be pranksters, reincarnations of mischievous spirits of the past or even those that have fallen far away from home. Their mushroom like appearance hides what appear to be intentions both good and bad, some claim to have been saved in their hour of need, while others still claim to have seen hideous rituals and gruesome sights at Poregon camps. Caution is advised.",
};

export const theGreenInk: Partial<ActorOptions> = {
  glyph: "GreenInk1",
  name: "ink",
  article: "the",
  colour: "green",
  inky: true,
  obeysGravity: false,
  maxHp: 160,
  maxHpRange: 175,
  sp: 38,
  spRange: 42,
  dp: 25,
  dpRange: 29,
  experience: 3000,
  teleportThreshold: 30,
  lore: "\"Whatever this hideous creature is, it's far from cognizant of what's occurring around it. Exploding younglings spurn forth endlessly from this flying yolk of terror, as if ink dripping on tarnished paper. I must report this finding, I must know why it is here, and I know I must be closer than ever to the Wisher's Fragment.\" - Jacques Splintertooth",
};
export const popper: Partial<ActorOptions> = {
  glyph: "InkPopper",
  name: "popper",
  colour: "green",
  ai: "fly", // TODO: explodes 5 turns after spawning
  inky: true,
  obeysGravity: false,
  maxHp: 4,
  maxHpRange: 6,
  sp: 50,
  dp: 8,
  dpRange: 10,
  experience: 800,
  lore: '"A strange mucus sack seems to encase these skull-like younglings, or perhaps the sack is the volatile chemical that causes these beasts to erupt in defence of their horrifying parental figure. I must steer clear of these nuisances, or deal with them quickly lest I am done irrevocable harm." - Jacques Splintertooth',
};

export const theRedInk: Partial<ActorOptions> = {
  glyph: "RedInk1",
  name: "ink",
  article: "the",
  colour: "red",
  inky: true,
  obeysGravity: false,
  maxHp: 230,
  maxHpRange: 260,
  sp: 45,
  spRange: 48,
  dp: 33,
  dpRange: 36,
  experience: 3000,
  teleportThreshold: 30,
  // TODO: leaves fire when teleporting
  lore: "\"Whatever this hideous creature is, it's far from cognizant of what's occurring around it. Extreme heat emanates all around this flying yolk of terror, all while it parades a legion of faces that sag like ink saturated paper. I must report this finding, I must know why it is here, and I know I must be closer than ever to the Wisher's Fragment.\" - Jacques Splintertooth",
};

// TODO: the blot

export const crate: Partial<ActorOptions> = {
  glyph: "Crate",
  name: "crate",
  colour: "brown",
  durability: 2,
  pushable: true,
};

export const boulder: Partial<ActorOptions> = {
  glyph: "Boulder",
  name: "boulder",
  colour: "grey",
  durability: 5,
  pushable: true,
  heavy: true,
};

export const metal: Partial<ActorOptions> = {
  glyph: "MetalBlock",
  name: "metal block",
  colour: "cyan",
  durability: 10,
  pushable: true,
  heavy: true,
};
